apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: decision-router
  namespace: asya-e2e
spec:
  transport: sqs
  scaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    queueLength: 1
  workload:
    kind: Deployment
    template:
      spec:
        containers:
        - name: asya-runtime
          image: actor-mesh-asya:dev
          env:
          - name: ASYA_HANDLER
            value: "handlers.decision_router.DecisionRouter.process"
          - name: ASYA_HANDLER_MODE
            value: "envelope"
